nohup: ignoring input
WARNING:matplotlib.font_manager:findfont: Font family ['FangSong'] not found. Falling back to DejaVu Sans.
ERROR:server:Exception on /wave [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 76, in wave
    X = data_service.data_conv_int(X)
  File "/var/www/flaskapp/services/data_service.py", line 14, in data_conv_int
    data = int(data)*1000
ValueError: invalid literal for int() with base 10: '6.7'
ERROR:server:Exception on /wave [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 76, in wave
    X = data_service.data_conv_int(X)
  File "/var/www/flaskapp/services/data_service.py", line 14, in data_conv_int
    data = int(data)*1000
ValueError: invalid literal for int() with base 10: '6.7'
ERROR:server:Exception on /wave [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 76, in wave
    X = data_service.data_conv_int(X)
  File "/var/www/flaskapp/services/data_service.py", line 14, in data_conv_int
    data = int(data)*1000
ValueError: invalid literal for int() with base 10: '6.7'
WARNING:matplotlib.font_manager:findfont: Font family ['FangSong'] not found. Falling back to DejaVu Sans.
WARNING:matplotlib.font_manager:findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
ERROR:server:Exception on /wave [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 76, in wave
    X = data_service.data_conv_int(X)
  File "/var/www/flaskapp/services/data_service.py", line 14, in data_conv_int
    data = int(data)*1000
ValueError: invalid literal for int() with base 10: '6.7'
ERROR:server:Exception on /wave [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "server.py", line 76, in wave
    X = data_service.data_conv_int(X)
  File "/var/www/flaskapp/services/data_service.py", line 14, in data_conv_int
    data = int(data)*1000
ValueError: invalid literal for int() with base 10: '20.'
